[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:is_face(from_boss)"
position = "after"
payload = '''
	if #SMODS.find_card("j_joaf_the_witness") > 0 then
		return false
	end
'''
match_indent = true